
# Neighborhood Normalization Rules
# Generated from previous migration data

# Manual mappings for empty/non-alphanumeric neighborhoods (by CNPJ)
CNPJ_TO_BAIRRO = {
    "34274233012534": "Val-de-Cães",
    "00394429006141": "Souza",
    "00807813000198": "Tapanã",
    "33163718001200": "Campina",
    "04902979007076": "Pedreira",
    "07095169000200": "Telegrafo",
    "26989350054046": "Nazaré",
    "33654419000388": "Marco",
    "33673294000333": "Umarizal",
    "33989468000533": "Umarizal",
    "33078585000111": "Pratinha",
    "60964996000934": "Reduto",
    "63031868003356": "Marco",
    "26988410001239": "Campina",
    "33618323001506": "Campina",
    "00003442000272": "Campina",
    "12268181000897": "Campina",
    "04905477000258": "Telegrafo",
    "00394536001615": "Nazaré",
    "33337122004203": "Val-de-Cães",
    "33685686001394": "Marco",
    "04920286000265": "Cidade Velha",
    "00394502014951": "Telegrafo",
    "00394429002154": "Val-de-Cães",
    "00394502015257": "Val-de-Cães",
    "13259189000930": "Curió-Utinga",
    "33683111000360": "Terra Firme",
}

# Standard normalization mappings (original -> normalized)
BAIRRO_NORMALIZATION = {
    "": "Val-de-Cães",  # Default for empty (will be overridden by CNPJ lookup)
    "(VILA) MOSQUEIRO": "Vila",
    "0427": "Curió-Utinga",
    "66113010": "Fátima",
    "ACAMPAMENTO": "Pedreira",
    "ACOARACI": "Campina de Icoaraci",
    "AEROCLUBE": "Souza",
    "AEROPORTO": "Aeroporto",
    "AEROPORTO - MOSQUEIRO": "Aeroporto",
    "AEROPORTO (MOSQUEIRO)": "Aeroporto",
    "AEROPORTO VAL DE CANS": "Aeroporto",
    "AGUA BOA": "São João do Outeiro",
    "AGUA BOA - OUTEIRO": "São João do Outeiro",
    "AGUA BOA (OUTEIRO)": "São João do Outeiro",
    "ÁGUA BOA (OUTEIRO)": "São João do Outeiro",
    "AGUA BOA / SAO JOAO DO OUTEIRO": "São João do Outeiro",
    "AGUA BOA-OUTEIRO": "São João do Outeiro",
    "AGUA BOA/OUTEIRO": "São João do Outeiro",
    "AGUAS LINDAS": "Águas Lindas",
    "ÁGUAS LINDAS": "Águas Lindas",
    "AGUAS NEGRAS": "Águas Negras",
    "AGUAS NEGRAS - ICOARACI": "Águas Negras",
    "AGUAS NEGRAS (ICOARACI)": "Águas Negras",
    "ÁGUAS NEGRAS (ICOARACI)": "Águas Negras",
    "AGUAS NEGRAS- ICOARACI": "Águas Negras",
    "AGUAS NEGRAS/ICOARACI": "Águas Negras",
    "AGULHA": "Agulha",
    "AGULHA  ICOARACI": "Agulha",
    "AGULHA - ICOARACI": "Agulha",
    "AGULHA (ICOARACI)": "Agulha",
    "AGULHA (ICOARACY)": "Agulha",
    "AGULHA / ICOARACI": "Agulha",
    "AGULHA DE ICOARACI": "Agulha",
    "AGULHA ICOARACI": "Agulha",
    "AGULHA INCOARACI66811120": "Agulha",
    "AGULHA-ICOARACI": "Agulha",
    "AGULHA(ICOARACI)": "Agulha",
    "AGULHA/ICOARACI": "Agulha",
    "ALPHAVILLE": "Águas Lindas",
    "AMAMBAIA": "Marambaia",
    "AREA RURAL DE BELEM": "Ilha do Combu",
    "AREA RURAL DE BELÉM": "Ilha do Combu",
    "ARIRAMBA": "Ariramba",
    "ARIRAMBA (MOSQUEIRO)": "Ariramba",
    "ARSENAL": "Jurunas",
    "ATALAIA": "Vila",
    "AURA": "Aurá",
    "AV NAZARE": "Nazaré",
    "B CAMPOS": "Batista Campos",
    "B VAL PARAISO": "Paraíso",
    "B. CAMPOS": "Batista Campos",
    "B.BATISTA CAMPOS": "Batista Campos",
    "BAIA DO SOL": "Baía do Sol",
    "BAIA DO SOL  MOSQUEIRO": "Baía do Sol",
    "BAIA DO SOL (MOSQUEIRO)": "Baía do Sol",
    "BAIRRO BATISTA CAMPOS": "Batista Campos",
    "BAIRRO DA PEDREIRA": "Pedreira",
    "BAIRRO DE NAZARE": "Nazaré",
    "BAIRRO DO CRUZEIRO": "Cruzeiro",
    "BAIRRO DO FIDELIS": "São João do Outeiro",
    "BAIRRO DO MARCO": "Marco",
    "BAIRRO DO REDUTO": "Reduto",
    "BAIRRO DO TELEGRAFO": "Telegrafo",
    "BAIRRO MARCO": "Marco",
    "BAIRRO PEDREIRA": "Pedreira",
    "BAIRRO SOUZA": "Souza",
    "BAIRRO TELEGRAFO": "Telegrafo",
    "BARREIRO": "Barreiro",
    "BARREIROS": "Barreiro",
    "BARRO-BRANCO": "São João do Outeiro",
    "BATISTA  CAMPOS": "Batista Campos",
    "BATISTA CAMOS": "Batista Campos",
    "BATISTA CAMPO": "Batista Campos",
    "BATISTA CAMPOS": "Batista Campos",
    "BATSITA CAMPOS": "Batista Campos",
    "BELEM": "Campina",  # Default for generic "BELEM"
    "BELEM CONTINENTAL": "Coqueiro",
    "BENEVIDES": "Benguí",
    "BENGUI": "Benguí",
    "BENGUI SAO CLEMENTE": "São Clemente",
    "BENGUI-JDM LIBERDADE": "Benguí",
    "BOA ESPERANCA": "Tapanã",
    "BOM FUTURO": "Parque Verde",
    "BONFIM (MOSQUEIRO)": "Bonfim",
    "BRASILIA": "Brasília",
    "BRASILIA (OUTEIRO)": "Brasília",
    "BRASÍLIA (OUTEIRO)": "Brasília",
    "BRASILIA OUTEIRO": "Brasília",
    "BRASILIA-OUTEIRO": "Brasília",
    "BRASILIA(OUTEIRO)": "Brasília",
    "BRASILIA/OUTEIRO": "Brasília",
    "BRASILIZA/OUTEIRO": "São João do Outeiro",
    "BRASLIA / DAOUT": "São João do Outeiro",
    "CABANAGEM": "Cabanagem",
    "CABANAGEM II": "Cabanagem",
    "CABANAGEMM": "Cabanagem",
    "CAIS DO PORTO": "Reduto",
    "Campina": "Campina",
    "CAMPINA": "Campina",
    "CAMPINA  - ICOARACI": "Campina",
    "CAMPINA - ICOARACI": "Campina",
    "CAMPINA (ICOARACI)": "Campina",
    "CAMPINA / ICOARACI": "Campina",
    "CAMPINA DE ICOARACI": "Campina de Icoaraci",
    "CAMPINA DE ICOARACI (ICOARACI)": "Campina de Icoaraci",
    "CAMPINA DE ICOARACI, DISTRITO DE ICOARACI": "Campina de Icoaraci",
    "CAMPINA DE ICORACI": "Campina",
    "CAMPINA- ICOARACI": "Campina",
    "CAMPINA-ICOARACI": "Campina",
    "CAMPINAS": "Campina",
    "CAMPNA": "Campina",
    "CAMPOS": "Campina",
    "CANTINA": "Campina",
    "CANUDO": "Canudos",
    "CANUDOS": "Canudos",
    "CAPINA": "Campina",
    "CARANANDUBA": "Carananduba",
    "CARANANDUBA (MOSQUEIRO)": "Carananduba",
    "CARANANDUBA(MOSQUEIRO)": "Carananduba",
    "CARMELANDIA": "Mangueirão",
    "CARUARA (MOSQUEIRO)": "Caruara",
    "CASTANHEIRA": "Castanheira",
    "CASTENHEIRA": "Castanheira",
    "CATALINA": "Mangueirão",
    "CEBTRO": "Campina",
    "CENTRO": "Campina",
    "CENTRO-ICOARACI": "Campina de Icoaraci",
    "CENTRO/MOSQUEIRO": "Vila",
    "CHA II": "Campina",
    "CHAPEU VIRADO": "Chapéu Virado",
    "CHAPEU VIRADO - MOSQUEIRO": "Chapéu Virado",
    "CHAPEU VIRADO (MOSQUEIRO)": "Chapéu Virado",
    "CHAPÉU VIRADO (MOSQUEIRO)": "Chapéu Virado",
    "CHAPEU VIRADO(MOSQUEIRO)": "Chapéu Virado",
    "CHAPEU VIRADO/MOSQUEIRO": "Chapéu Virado",
    "CHAPEU-VIRADO": "Chapéu Virado",
    "CIADADE VELHA": "Cidade Velha",
    "CID VELHA": "Cidade Velha",
    "CIDADE": "Cidade Velha",
    "CIDADE VELHA": "Cidade Velha",
    "CIDADE VELHA/ BELEM": "Cidade Velha",
    "CIDADE VELHA3": "Cidade Velha",
    "CIDADE VELJHA": "Cidade Velha",
    "CIDADE-VELHA": "Cidade Velha",
    "COHAB ICOARACI": "Campina de Icoaraci",
    "COL PINHEIRO": "Agulha",
    "COMBU": "Ilha do Combu",
    "COMERCIAL": "Campina",
    "COMERCIO": "Campina",
    "COMERCIO BELEM(PA)": "Campina",
    "COMRCIO": "Campina",
    "CONDOR": "Condor",
    "CONDUR": "Condor",
    "CONJ PANORAMA XXI": "Mangueirão",
    "CONJ RES MAGUARI": "Coqueiro",
    "CONJ. JARDIM MAGUARI": "Coqueiro",
    "CONJUNTO JARDIM": "Benguí",
    "CONJUNTO MAGUARI": "Coqueiro",
    "COPNDOR": "Condor",
    "COQUEIRO": "Coqueiro",
    "CORREIOS": "Marambaia",
    "COTIJUBA": "Ilha de Cotijuba",
    "COTIJUBA CENTRO": "Ilha de Cotijuba",
    "CRAMACAO": "Cremação",
    "CREMACAO": "Cremação",
    "CREMAÇÃO": "Cremação",
    "CREMACAO II": "Cremação",
    "CREMAO": "Cremação",
    "CREMCAO": "Cremação",
    "CRENACAO": "Cremação",
    "CRUZEIRO": "Cruzeiro",
    "CRUZEIRO - ICOARACI": "Cruzeiro",
    "CRUZEIRO ( ICOARACI )": "Cruzeiro",
    "CRUZEIRO (ICOARACI)": "Cruzeiro",
    "CRUZEIRO / ICOARACI": "Cruzeiro",
    "CRUZEIRO DE ICOARACI": "Cruzeiro",
    "CRUZEIRO ICOARACI": "Cruzeiro",
    "CRUZEIRO-ICOARACI": "Cruzeiro",
    "CRUZEIRO(ICOARACI)": "Cruzeiro",
    "CRUZEIRO/ ICOARACI": "Cruzeiro",
    "CRUZEIRO/*ICOARACI": "Cruzeiro",
    "CRUZEIRO/ICOARACI": "Cruzeiro",
    "CURIO": "Curió-Utinga",
    "CURIÓ": "Curió-Utinga",
    "CURIO - UTINGA": "Curió-Utinga",
    "CURIO UTINGA": "Curió-Utinga",
    "CURIO-UTINGA": "Curió-Utinga",
    "CURIÓ-UTINGA": "Curió-Utinga",
    "CURIO/UTINGA": "Curió-Utinga",
    "CUTIJUBA": "Ilha de Cotijuba",
    "DA BRASILIA": "Brasília",
    "DAS MANGUEIRAS": "Mangueiras",
    "DE FATIMA": "Fátima",
    "DIST IND DE ICOARACI": "Maracacuera",
    "DISTRITO ADMINISTRATIVO DE OUTEIRO": "São João do Outeiro",
    "DISTRITO DE ICOARACI": "Campina de Icoaraci",
    "DISTRITO DE MOSQUEIRO": "Vila",
    "DISTRITO DO OUTEIRO": "São João do Outeiro",
    "DISTRITO INDUSTRIAL": "Maracacuera",
    "DISTRITO INDUSTRIAL DE ICOARACI": "Maracacuera",
    "DISTRITO INDUSTRIAL DE ICOARACI - MARACACUERA": "Maracacuera",
    "DISTRITO INDUSTRIAL ICOARACI": "Maracacuera",
    "DISTRITO INDUTRIAL": "Maracacuera",
    "DO GUAMA": "Guamá",
    "DO MARCO": "Marco",
    "DO PARA": "Guamá",
    "DO TELEGRAFO": "Telegrafo",
    "DOCAS": "Reduto",
    "EDIFICIO NOBRE": "Campina",
    "ENTOCAMENTO": "Castanheira",
    "ENTROCAMENTO": "Castanheira",
    "ENTRONCAMENTO": "Castanheira",
    "ESTRADA DE ICOARACI": "Campina de Icoaraci",
    "ESTRADA DO COQUEIRO": "Coqueiro",
    "ESTRADA NOVA": "Jurunas",
    "FAMA": "Tapanã",
    "FAROL": "Farol",
    "FAROL (MOSQUEIRO)": "Farol",
    "FATIMA": "Fátima",
    "FÁTIMA": "Fátima",
    "FE EM DEUS": "Guamá",
    "FIDELIS (OUTEIRO)": "São João do Outeiro",
    "FIDELIS-DISTRITO DE OUTEIRO": "São João do Outeiro",
    "FIO VAL DE CAES": "Val-de-Cães",
    "FURO DAS MARINHAS": "Carananduba",
    "GUAM": "Guamá",
    "GUAMA": "Guamá",
    "GUAMÁ": "Guamá",
    "GUAMA II": "Guamá",
    "GUAMA III": "Guamá",
    "GUANABARA": "Guanabara",
    "GUANABARA I": "Guanabara",
    "HUMARIZAL": "Umarizal",
    "ICOARACI": "Campina de Icoaraci",
    "ICOARACI - OUTEIRO": "Campina de Icoaraci",
    "ICOARACI AGULHA": "Agulha",
    "ICOARACI BELEM": "Campina de Icoaraci",
    "ICOARACI/CRUZEIRO": "Cruzeiro",
    "ICOARACY": "Campina de Icoaraci",
    "ICOARAI": "Campina de Icoaraci",
    "ICORACI": "Campina de Icoaraci",
    "ICORACI-TAPANA": "Tapanã",
    "ICORACY": "Campina de Icoaraci",
    "IGARAPE AURA": "Aurá",
    "IGARAPE DO COMBU": "Ilha do Combu",
    "IGARAPE LARANJEIRAS": "Ilha do Combu",
    "IGARAPE PIRIQUITAQUARA": "Ilha do Combu",
    "ILHA DA VARZEA": "Ilha do Combu",
    "ILHA DE COTIJUBA": "Ilha de Cotijuba",
    "ILHA DO COMBU": "Ilha do Combu",
    "ILHA DO CUMBÚ": "Ilha do Combu",
    "ILHA DO MURUTUCU": "Ilha do Combu",
    "ILHA DO OUTEIRO - DISTRITO DE ICOARACI": "Campina de Icoaraci",
    "ILHA GRANDE": "Ilha do Combu",
    "ILHA MURUCUTU": "Ilha do Combu",
    "ILHAS DO COMBU": "Ilha do Combu",
    "ILHAS DO CUMBU": "Ilha do Combu",
    "INDEPENDENCIA": "Cabanagem",
    "INDUSTRIAL": "Maracacuera",
    "IPEAN": "Marco",
    "IPIXUNA": "Una",
    "ITAITEUA": "Itaiteua",
    "ITAITEUA (OUTEIRO)": "Itaiteua",
    "ITAITEUA / OUTEIRO": "Itaiteua",
    "ITAITEUA DISTRITO DE OUTEIRO": "Itaiteua",
    "ITAITEUA OUTEIRO": "Itaiteua",
    "ITAITEUA-OUTEIRO": "Itaiteua",
    "ITAITEVA": "Itaiteua",
    "JABATITEUA": "Marco",
    "JADERLAR": "Cabanagem",
    "JARARACA": "Ilha do Combu",
    "JARDIM ESMERALDA": "Águas Lindas",
    "JARDIM GUANABARA": "Guanabara",
    "JD PRIMAVERA": "Benguí",
    "JDM SIDERAL": "Coqueiro",
    "JIBOIA BRANCA": "Coqueiro",
    "JOAO BRAZ": "São Brás",
    "JURUNAS": "Jurunas",
    "JURUNAS I": "Jurunas",
    "JURUNAS NOVO": "Jurunas",
    "JURUNAS''": "Jurunas",
    "JURUNAS(ARSENAL)": "Jurunas",
    "LOT JD UBERABA": "Coqueiro",
    "MAGUEIRAO": "Mangueirão",
    "MANGEIRAO": "Mangueirão",
    "MANGEIRAS": "Mangueiras",
    "MANGUEIRA": "Mangueiras",
    "MANGUEIRAO": "Mangueirão",
    "MANGUEIRÃO": "Mangueirão",
    "MANGUEIRAS": "Mangueiras",
    "MANGUEIRAS (MOSQUEIRO)": "Mangueiras",
    "MANGUEIRO": "Mangueirão",
    "MANQUEIRAO": "Mangueirão",
    "MARACACUERA": "Maracacuera",
    "MARACACUERA (ICOARACI)": "Maracacuera",
    "MARACACUERA ICOARACI": "Maracacuera",
    "MARACACUERA-DIST. IND. DE ICOARACI": "Maracacuera",
    "MARACACUERA-DISTRITO I. DE ICOARACI": "Maracacuera",
    "MARACACUERA-ICOARACI": "Maracacuera",
    "MARACACUERA(DISTRITO DE ICOARACI)": "Maracacuera",
    "MARACACUERA(ICOARACI)": "Maracacuera",
    "MARACACUERA/ICOARACI": "Maracacuera",
    "MARACAJA": "Maracajá",
    "MARACAJA (MOSQUEIRO)": "Maracajá",
    "MARACAJÁ (MOSQUEIRO)": "Maracajá",
    "MARACAJA / MOSQUEIRO": "Maracajá",
    "MARACAMGALHA": "Maracangalha",
    "MARACANGALHA": "Maracangalha",
    "MARACAQUERA": "Maracacuera",
    "MARAGANGALHA": "Maracangalha",
    "MARAHU": "Marahu",
    "MARAHU (MOSQUEIRO)": "Marahu",
    "MARAMABAIA": "Marambaia",
    "MARAMBAIA": "Marambaia",
    "MARAMBAIA II": "Marambaia",
    "MARAMBAIA": "Marambaia",
    "MARAMBIA": "Marambaia",
    "MARANCAGALHA": "Maracangalha",
    "MARANGALHA": "Maracangalha",
    "MARCC": "Marco",
    "MARCO": "Marco",
    "MARCO DA LEGUA": "Marco",
    "MARCO RAMAL UTINGA": "Marco",
    "MARCO/BELEM": "Marco",
    "MARI MARI  -  MOSQUEIRO": "Vila",
    "MATINHA": "Fátima",
    "MENDARA": "Marambaia",
    "MIRAMAR": "Miramar",
    "MONTESE": "Terra Firme",
    "MONTESES": "Terra Firme",
    "MORUBIRA": "Murubira",
    "MOSQUEIRO": "Vila",
    "MUNICIPALIDADE": "Reduto",
    "MURUBIRA": "Murubira",
    "MURUBIRA (MOSQUEIRO)": "Murubira",
    "MURUBIRA(MOSQUEIRO)": "Murubira",
    "MURUBIRA/MOSQUEIRO": "Murubira",
    "N A Z A R E": "Nazaré",
    "N MARAMBAIA": "Marambaia",
    "N. MARAMBAIA": "Marambaia",
    "N.MARAMBAIA": "Marambaia",
    "N.MURUBIRA-MOSQUEIRO": "Murubira",
    "NARAZE": "Nazaré",
    "NATAL DO MURUBIRA (MOSQUEIRO)": "Murubira",
    "NAZAR": "Nazaré",
    "NAZARA": "Nazaré",
    "NAZARE": "Nazaré",
    "NAZARÉ": "Nazaré",
    "NAZARE / BELEM": "Nazaré",
    "NAZERE": "Nazaré",
    "NOSSA SENHORA DE FATIMA": "Fátima",
    "NOVA  MARAMBAIA": "Marambaia",
    "NOVA MARAMBAIA": "Marambaia",
    "OEDREIRA": "Pedreira",
    "OUTEIRO": "São João do Outeiro",
    "OUTEIRO-DISTRITO DE ICOARACI": "Campina de Icoaraci",
    "PARACURI": "Paracuri",
    "PARACURI -ICOARACI": "Paracuri",
    "PARACURI (ICOARACI)": "Paracuri",
    "PARACURI ICOARACI": "Paracuri",
    "PARACURI II": "Paracuri",
    "PARACURI II/ICOARACI": "Paracuri",
    "PARACURI-ICOARACI": "Paracuri",
    "PARAISO": "Paraíso",
    "PARAISO (MOSQUEIRO)": "Paraíso",
    "PARAISO MOSQUEIRO": "Paraíso",
    "PARQUE GUAJARA": "Parque Guajará",
    "PARQUE GUAJARA - ICOARACI": "Parque Guajará",
    "PARQUE GUAJARA (ICOARACI)": "Parque Guajará",
    "PARQUE GUAJARÁ (ICOARACI)": "Parque Guajará",
    "PARQUE GUAJARA / ICOARACI": "Parque Guajará",
    "PARQUE GUAJARA ICOARACI": "Parque Guajará",
    "PARQUE GUAJARA/ICOARACI": "Parque Guajará",
    "PARQUE GUARUJA": "Parque Guajará",
    "PARQUE VERDE": "Parque Verde",
    "PARQUE VERDE/ BENGUI": "Parque Verde",
    "PEDREIRA": "Pedreira",
    "PEDREIRA III": "Pedreira",
    "PEDREIRAS": "Pedreira",
    "PICARREIRA": "Pedreira",
    "PONTA GROSSA": "Ponta Grossa",
    "PONTA GROSSA - ICOARACI": "Ponta Grossa",
    "PONTA GROSSA (ICOARACI)": "Ponta Grossa",
    "PONTA GROSSA / ICOARACI": "Ponta Grossa",
    "PONTA GROSSA ICOARACI": "Ponta Grossa",
    "PONTA GROSSA-ICOARACI": "Ponta Grossa",
    "PONTA GROSSA(ICOARACI)": "Ponta Grossa",
    "PONTA GROSSA/ ICOARACI": "Ponta Grossa",
    "PONTA GROSSA/ICOARACI": "Ponta Grossa",
    "PORCAO": "Ilha de Cotijuba",
    "PORTO ARTHUR": "Porto Arthur",
    "PORTO ARTHUR (MOSQUEIRO)": "Porto Arthur",
    "PORTO ARTUR": "Porto Arthur",
    "PORTO METRALHADORA": "Jurunas",
    "PRAIA DA BRASILIA": "Brasília",
    "PRAIA GRANDE": "Praia Grande",
    "PRAIA GRANDE (MOSQUEIRO)": "Praia Grande",
    "PRATINHA": "Pratinha",
    "PRATINHA  1": "Pratinha",
    "PRATINHA (ICOARACI)": "Pratinha",
    "PRATINHA / ICOARACI": "Pratinha",
    "PRATINHA 1": "Pratinha",
    "PRATINHA I": "Pratinha",
    "PRATINHA ICOARACI": "Pratinha",
    "PRATINHA II": "Pratinha",
    "PRATINHA/ICOARACI": "Pratinha",
    "PRATINHAII": "Pratinha",
    "REDURO": "Reduto",
    "REDUTO": "Reduto",
    "RODOVIA": "Campina de Icoaraci",
    "S BRAZ": "São Brás",
    "S.BRAZ": "São Brás",
    "SA0  BRAZ": "São Brás",
    "SACARAMENTA": "Sacramenta",
    "SACRAMENTA": "Sacramenta",
    "SACRAMENTA III PEDR": "Sacramenta",
    "SACRAMENTA IV": "Sacramenta",
    "SACRAMENTO": "Sacramenta",
    "SALETE": "Tapanã",
    "SANTA ISABEL": "Benguí",
    "SANTA IZABEL": "Guamá",
    "SANTA LUZIA": "Umarizal",
    "SAO   BRAZ": "São Brás",
    "SAO  BRAZ": "São Brás",
    "SAO BRAS": "São Brás",
    "SÃO BRÁS": "São Brás",
    "SAO BRAS/GUAMA": "São Brás",
    "SAO BRAZ": "São Brás",
    "SAO CLEMENTE": "São Clemente",
    "SÃO CLEMENTE": "São Clemente",
    "SAO FRANCISCO": "São Francisco",
    "SAO FRANCISCO - MOSQUEIRO": "São Francisco",
    "SAO FRANCISCO (MOSQUEIRO)": "São Francisco",
    "SÃO FRANCISCO (MOSQUEIRO)": "São Francisco",
    "SAO JOAO DO BRUNO": "São João do Outeiro",
    "SAO JOAO DO OUTEIRO": "São João do Outeiro",
    "SAO JOAO DO OUTEIRO (OUTEIRO)": "São João do Outeiro",
    "SÃO JOÃO DO OUTEIRO (OUTEIRO)": "São João do Outeiro",
    "SAO JOAO DO OUTEIRO OUTEIRO": "São João do Outeiro",
    "SEDE": "Campina",
    "SETOR MARAMBAIA": "Marambaia",
    "SIDERAL": "Coqueiro",
    "SO BRAS": "São Brás",
    "SO BRAZ": "São Brás",
    "SOA BRAZ": "São Brás",
    "SOUSA": "Souza",
    "SOUZA": "Souza",
    "SUCURIJUGUARA": "Sucurijuquara",
    "SUCURIJUQUARA": "Sucurijuquara",
    "SUCURIJUQUARA (MOSQUEIRO)": "Sucurijuquara",
    "TAPANA": "Tapanã",
    "TAPANÃ": "Tapanã",
    "TAPANA  (ICOARACI)": "Tapanã",
    "TAPANA (ICOARACI)": "Tapanã",
    "TAPANÃ (ICOARACI)": "Tapanã",
    "TAPANA / ICOARACI": "Tapanã",
    "TAPANA ICOARACI": "Tapanã",
    "TAPANA(ICOARACI)": "Tapanã",
    "TAPANA/ICOARACI": "Tapanã",
    "TEEGRAFO": "Telegrafo",
    "TELEGAFO SEM FIO": "Telegrafo",
    "TELEGRAFO": "Telegrafo",
    "TELEGRAFO  SEM FIO": "Telegrafo",
    "TELEGRAFO SEM FIO": "Telegrafo",
    "TELÉGRAFO SEM FIO": "Telegrafo",
    "TELEGRAFO SEM FIO ( BARREIRO )": "Telegrafo",
    "TELELGRAFO": "Telegrafo",
    "TELGRAFO": "Telegrafo",
    "TELGRAFO SEM FIO": "Telegrafo",
    "TENON E": "Tenoné",
    "TENONE": "Tenoné",
    "TENONÉ": "Tenoné",
    "TENONE / ICOARACI": "Tenoné",
    "TERRA  FIRME": "Terra Firme",
    "TERRA - FIRME (MONTESE)": "Terra Firme",
    "TERRA FIRME": "Terra Firme",
    "TERRA FRIME": "Terra Firme",
    "TERRAFIRME": "Terra Firme",
    "TOCANTINS": "Tapanã",
    "UAMRIZAL": "Umarizal",
    "UMARIAZAL": "Umarizal",
    "UMARISAL": "Umarizal",
    "UMARIZAL": "Umarizal",
    "UMJARIZAL": "Umarizal",
    "UNA": "Una",
    "UNIVERSITARIO": "Universitário",
    "VAL - DE - CAES": "Val-de-Cães",
    "VAL - DE - CANS": "Val-de-Cães",
    "VAL -DE-CANS": "Val-de-Cães",
    "VAL DE CAES": "Val-de-Cães",
    "VAL DE CANS": "Val-de-Cães",
    "VAL DE CANZ": "Val-de-Cães",
    "VAL- DE- CAES": "Val-de-Cães",
    "VAL- DE-CANS": "Val-de-Cães",
    "Val-de-Caes": "Val-de-Cães",
    "VAL-DE-CAES": "Val-de-Cães",
    "VAL-DE-CÃES": "Val-de-Cães",
    "VAL-DE-CAES (CONJUNTO BELA VISTA)": "Val-de-Cães",
    "VAL-DE-CANS": "Val-de-Cães",
    "VALDCAES": "Val-de-Cães",
    "VALDECAES": "Val-de-Cães",
    "VILA": "Vila",
    "VILA (DISTRITO DE MOSQUEIRO)": "Vila",
    "VILA (MOSQUEIRO)": "Vila",
    "VILA DE ICOARACI": "Campina de Icoaraci",
    "VILA DE ICOARACY": "Vila",
    "VILA DE MOSQUEIRO": "Vila",
    "VILA DO MOSQUEIRO": "Vila",
    "VILA ICOARACI": "Campina de Icoaraci",
    "VILA MOSQUEIRO": "Vila",
    "VILA NOVA ESPERANCA DAS BARREIRAS": "Vila",
    "VILA, DISTRITO DE MOSQUEIRO": "Vila",
    "VILA(MOSQUEIRO": "Vila",
    "VILA(MOSQUEIRO)": "Vila",
    "VILA(MOSQUIERO)": "Vila",
    "VILA/MOSQUEIRO": "Vila",
    "VL ICOARACY": "Campina de Icoaraci",
    "ZONA RURAL": "Vila",
    "ZONA URBANA": "Curió-Utinga",
}

import re

def normalize_bairro(bairro_original, cnpj_full=None):
    """
    Normalize a neighborhood name.
    
    Args:
        bairro_original: Original neighborhood string from database
        cnpj_full: Full CNPJ (14 digits) for empty/special cases
    
    Returns:
        Normalized neighborhood name
    """
    # Clean the input
    bairro = (bairro_original or "").strip()
    
    # Check if empty or non-alphanumeric
    if not bairro or not re.search(r'[a-zA-Z0-9]', bairro):
        # Use CNPJ lookup for empty/non-alphanumeric cases
        if cnpj_full:
            cnpj_clean = re.sub(r'\D', '', cnpj_full)
            if cnpj_clean in CNPJ_TO_BAIRRO:
                return CNPJ_TO_BAIRRO[cnpj_clean]
        return None  # Unknown
    
    # Try exact match first
    if bairro in BAIRRO_NORMALIZATION:
        return BAIRRO_NORMALIZATION[bairro]
    
    # Try uppercase match
    bairro_upper = bairro.upper()
    if bairro_upper in BAIRRO_NORMALIZATION:
        return BAIRRO_NORMALIZATION[bairro_upper]
    
    # No match found - leave empty
    return None
